// Generated by scripts/generate_contract_types.py. Do not edit.

export type UUID = string;
export type ISODateTime = string;

export interface ActionCard {
  kind: "action";
  action_id: string;
  label: string;
  url: string;
  external: boolean;
  requires_auth: boolean;
  auth_reason: string | null;
}

export interface SafeError {
  code: SafeErrorCode;
  message: string;
  retryable: boolean;
  next_action: ActionCard | null;
}

export interface SourceCard {
  kind: "source";
  source_id: string;
  title: string;
  url: string | null;
  retrieved_at: ISODateTime;
  as_of: ISODateTime | null;
  document_version: string | null;
}

export interface ProductCard {
  kind: "product";
  variant_id: UUID;
  model_name: string;
  model_year: number;
  variant_name: string;
  body_type: string | null;
  image_url: string | null;
  brochure_url: string | null;
}

export interface PriceCard {
  kind: "price";
  variant_id: UUID;
  branch_id: UUID | null;
  amount: AmountString | null;
  currency: CurrencyCode;
  availability: "available" | "not_available" | "unknown";
  lookup_status: "verified" | "unavailable" | "unknown";
  freshness: "current" | "stale" | "unknown";
  qualifiers: Array<string>;
  as_of: ISODateTime | null;
  expires_at: ISODateTime | null;
  message: string;
}

export interface ToolEnvelope {
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  tool_call_id: string;
  tool_name: string;
  status: ToolStatus;
  data: ToolCard | Array<ToolCard> | null;
  source_refs: Array<string>;
  as_of: ISODateTime | null;
  expires_at: ISODateTime | null;
  error: SafeError | null;
}

export interface ToolCallRequest {
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  tool_call_id: string;
  tool_name: string;
  arguments: Record<string, unknown>;
}

export interface ChatRequest {
  request_id: UUID;
  conversation_id: UUID;
  message: string;
  locale: string;
}

export interface RunCreatedResponse {
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  status: RunStatus;
}

export interface StatusEvent {
  event: "status";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  status: RunStatus;
  message: string;
}

export interface AnswerDeltaEvent {
  event: "answer_delta";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  delta: string;
  message_id: UUID | null;
}

export interface SourcesEvent {
  event: "sources";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  sources: Array<SourceCard>;
}

export interface CardsEvent {
  event: "cards";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  cards: Array<ProductCard | PriceCard | ActionCard>;
}

export interface DoneEvent {
  event: "done";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  message_id: UUID;
  status: "completed" | "cancelled";
}

export interface ErrorEvent {
  event: "error";
  request_id: UUID;
  conversation_id: UUID;
  run_id: UUID;
  trace_id: UUID;
  occurred_at: ISODateTime;
  error: SafeError;
}

export type ToolCard = SourceCard | ProductCard | PriceCard | ActionCard;

export type SseEvent =
  | StatusEvent
  | AnswerDeltaEvent
  | SourcesEvent
  | CardsEvent
  | DoneEvent
  | ErrorEvent;

export type SafeErrorCode =
  | "invalid_request"
  | "not_authenticated"
  | "not_authorized"
  | "not_found"
  | "unavailable"
  | "stale_data"
  | "conflict"
  | "rate_limited"
  | "timeout"
  | "cancelled"
  | "internal_error";

export type AmountString = string;

export type CurrencyCode = string;

export type ToolStatus =
  "success" | "empty" | "denied" | "unavailable" | "invalid_input";

export type RunStatus =
  "queued" | "running" | "validating" | "completed" | "cancelled";
