"""Generate frontend contract artifacts from the canonical Pydantic schemas."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pydantic import TypeAdapter  # noqa: E402

from app.api.contracts import API_CONTRACT_MODELS, SseEvent  # noqa: E402
from app.tools.contracts import TOOL_CONTRACT_MODELS, ToolCard  # noqa: E402

SCHEMA_PATH = ROOT / "frontend/src/types/api.schema.json"
TYPES_PATH = ROOT / "frontend/src/types/api.generated.ts"


def _schema_without_defs(schema: dict[str, Any], definitions: dict[str, Any]) -> dict[str, Any]:
    nested = schema.pop("$defs", {})
    definitions.update(nested)
    return schema


def build_schema() -> dict[str, Any]:
    definitions: dict[str, Any] = {}
    contracts: list[str] = []

    for model in [*TOOL_CONTRACT_MODELS, *API_CONTRACT_MODELS]:
        name = model.__name__
        schema = _schema_without_defs(
            model.model_json_schema(mode="serialization", ref_template="#/$defs/{model}"),
            definitions,
        )
        definitions[name] = schema
        contracts.append(name)

    for name, contract in (("ToolCard", ToolCard), ("SseEvent", SseEvent)):
        schema = _schema_without_defs(
            TypeAdapter(contract).json_schema(mode="serialization", ref_template="#/$defs/{model}"),
            definitions,
        )
        definitions[name] = schema
        contracts.append(name)

    for name in definitions:
        if name not in contracts:
            contracts.append(name)

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "contracts": contracts,
        "$defs": definitions,
    }


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "const" in schema:
        return _ts_string(schema["const"])
    if "enum" in schema:
        return " | ".join(_ts_string(value) for value in schema["enum"])
    if "anyOf" in schema or "oneOf" in schema:
        key = "anyOf" if "anyOf" in schema else "oneOf"
        members = [_ts_type(member) for member in schema[key]]
        unique = list(dict.fromkeys(members))
        return " | ".join(unique)
    if "allOf" in schema:
        return " & ".join(_ts_type(member) for member in schema["allOf"])
    schema_type = schema.get("type")
    if schema_type == "array":
        return f"Array<{_ts_type(schema.get('items', {}))}>"
    if schema_type == "object":
        if "properties" in schema:
            return _ts_object(schema)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_ts_type(additional)}>"
        return "Record<string, unknown>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        if schema.get("format") == "uuid":
            return "UUID"
        if schema.get("format") == "date-time":
            return "ISODateTime"
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    return "unknown"


def _ts_object(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines = ["{"]
    for name, property_schema in properties.items():
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_ts_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def build_typescript(schema: dict[str, Any]) -> str:
    lines = [
        "// Generated by scripts/generate_contract_types.py. Do not edit.",
        "",
        "export type UUID = string;",
        "export type ISODateTime = string;",
        "",
    ]
    for name in schema["contracts"]:
        definition = schema["$defs"][name]
        type_value = _ts_type(definition)
        if definition.get("type") == "object" and "properties" in definition:
            lines.append(f"export interface {name} {_ts_object(definition)}")
        else:
            lines.append(f"export type {name} = {type_value};")
        lines.append("")
    return "\n".join(lines)


def _prettier(text: str, parser: str) -> str:
    prettier = ROOT / "frontend/node_modules/.bin/prettier"
    if not prettier.exists():
        return text
    result = subprocess.run(
        [str(prettier), "--parser", parser],
        input=text,
        capture_output=True,
        check=True,
        text=True,
    )
    return result.stdout


def expected_outputs() -> tuple[str, str]:
    schema = build_schema()
    schema_text = _prettier(json.dumps(schema, indent=2, ensure_ascii=False), "json")
    types_text = _prettier(build_typescript(schema), "typescript")
    return schema_text, types_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    schema_text, types_text = expected_outputs()
    if args.check:
        stale = []
        if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text(encoding="utf-8") != schema_text:
            stale.append(str(SCHEMA_PATH.relative_to(ROOT)))
        if not TYPES_PATH.exists() or TYPES_PATH.read_text(encoding="utf-8") != types_text:
            stale.append(str(TYPES_PATH.relative_to(ROOT)))
        if stale:
            print("Generated contract artifacts are stale: " + ", ".join(stale))
            return 1
        print("Generated contract artifacts are current.")
        return 0

    SCHEMA_PATH.write_text(schema_text, encoding="utf-8")
    TYPES_PATH.write_text(types_text, encoding="utf-8")
    print(f"Generated {SCHEMA_PATH.relative_to(ROOT)}")
    print(f"Generated {TYPES_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
